name: test workflow
on: push
jobs:
  first_job:
    runs-on: ubunut-latest
    steps:
      - name: wlecome mesage
        run: echo "welcome to github actions"
      - name: second step
        run: echo "this is the second step"