name: Test Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Execting dependencies outsde of workflow      
        run: |
          chmod +x ./build_script.sh
          ./build_script.sh
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Test after build
        run: |
          chmod +x ./test_script.sh
          ./test_script.sh
  deploy:
    runs-on: ubuntu-latest  
    needs: [build, test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Deploy after test
        run: |
          echo "Deploying application..."
          chmod +x ./deploy_script.sh
          ./deploy_script.sh